# Generated by Django 6.0.7 on 2026-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_cover/'),
        ),
    ]
