# Generated by Django 6.0.7 on 2026-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageimage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_cover/'),
        ),
    ]
