# Generated by Django 6.0.7 on 2026-07-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_packageimage_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageimage',
            name='cover_image',
        ),
    ]
