# Generated by Django 6.0.7 on 2026-08-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_savedpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='route_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
