# Generated by Django 6.0.7 on 2026-07-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emergency_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_relationship',
        ),
    ]
