# Generated by Django 6.0.7 on 2026-07-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_email_company_is_active_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_feedback',
            field=models.TextField(blank=True, help_text='Admin remarks for approval, rejection or suspension.', null=True),
        ),
    ]
