# Generated by Django 6.0.7 on 2026-07-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_admin_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approval_message_seen',
            field=models.BooleanField(default=False),
        ),
    ]
