# Generated by Django 6.0.7 on 2026-07-31 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_trekrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trekrequest',
            name='admin_feedback',
        ),
        migrations.RemoveField(
            model_name='trekrequest',
            name='created_at',
        ),
    ]
