# Generated by Django 6.0.7 on 2026-07-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('altitude', models.PositiveIntegerField(help_text='Maximum altitude in meters')),
                ('duration', models.PositiveIntegerField(help_text='Average duration in days')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Extreme', 'Extreme')], max_length=20)),
                ('image', models.ImageField(upload_to='treks/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treks', to='regions.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
