# Generated by Django 6.0.7 on 2026-07-25 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_approval_message_seen'),
        ('regions', '0001_initial'),
        ('treks', '0002_remove_trek_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrekRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trek_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('estimated_altitude', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Extreme', 'Extreme')], max_length=20)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='trek_requests/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trek_requests', to='companies.company')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
        ),
    ]
