# Generated by Django 6.0.7 on 2026-07-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0003_trekrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrekRequest',
        ),
    ]
