# Generated by Django 6.0.7 on 2026-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0004_delete_trekrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treks/'),
        ),
    ]
